#!/usr/bin/perl -w
# nginx_memory --- Munin plugin for monitoring Nginx memory usage. 

## Munin config method.
if (exists $ARGV[0] and $ARGV[0] eq "config") {
  print "graph_title nginx RAM usage\n";
  print "graph_vlabel RAM\n";
  print "graph_category nginx\n";
  print "ram.label RAM\n";
  print "graph_args --base 1024\n";

  exit 0;
} else {
  my $m = `ps u -p  \$(pidof nginx) | awk 'NR > 1 {nm += \$5} END {print nm*1024}'`;
  print "ram.value $m";
}
